### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by haohaoalt** [G-U-N/Restricted-Boltzmann-machine-for-AutoEncoder#1]
您好，您的这个源码是可以在其他机子上面运行成功吗？

**Comment by G-U-N** [comment]
你好，当然是可以运行成功的。运行失败的原因有很多种，最有可能的原因是因为你没有安装必要与恰当的包。

**Comment by haohaoalt** [comment]
感谢回复，原因应该是笔记本的性能开不了多线程，因此需要将num_workers（在utils.py中）设为0即可跑通

**Comment by G-U-N** [comment]
好的，感谢你的关注
